### PR TITLE
Support for caPutLog >= R3.5

### PR DESCRIPTION
**Pull request by hhslepicka**
This patch was originally made by @bhill-slac .

@bfrk changed the caPutLog and renamed the members of the VALUE union (See: https://github.com/epics-modules/caPutLog/commit/1fbe2ed1f7fe26ed9edc98fada7f96ecf033ab64)
This means that the ca-gateway will not build with versions of caPutLog greater than R3-4.

This Pull Request also adds the note at the README file that EPICS 7 needs PCAS as an external module to be added to the RELEASE file.

### CODE REVIEW

**Comment by bfrk** [comment]
The changes that actually do what the comment says look fine to me. However, the second patch "FIX: Adjust caPutLog dependent struct..." should, IMHO, be cleaned up before merging, as it contains lots of changes not related to the issue at hand (e.g. adding support for 64 bit request types). My recommendation would be to split the changes into semantically related sets and record them separately, for easier review.

**Comment by ralphlange** [comment]
@bfrk Thanks for lurking around!
Question: does the caPutLog change come with a preprocessor-testable thing (numerical version number or a new macro being defined)? I would prefer to avoid a versioned dependency to caPutLog in the Gateway, if possible.

**Comment by bfrk** [comment]
No, caPutLog doesn't have that (yet). Shouldn't be too hard to add, but of course it would be too late to help with the problem at hand.

**Comment by hhslepicka** [comment]
Ok... changes were split now into smaller commits. It is ready for a new review.

**Comment by bfrk** [comment]
This is a clear improvement, thanks. I recommend all changes for merging except "ENH: Add ca putLog support. " which I think still needs a bit of cleanup. The addition of gateResources::putLog in src/gateResources.cc/h is fine but the changes to src/gateVc.cc where the new method is called still confuse me. There are some layout/whitespace changes in there, not all of which look justified to me. More importantly, I am unclear about the how and why of the re-grouping of #ifdefs. Perhaps someone more familiar with this part of the gateway code can make more useful comments here. My impression is that some of the changes made to this file are meant as cleanup of the existing code, independent of the addition of the call to gateResources::putLog. If this is the case, these could be separated out and perhaps given a bit of explanation in the comment to the patch/commit.

I wonder why the Travix CI build fails. Perhaps this is due to unmet dependencies in the builder? Have you been abe to run the test suite (I assume there is one) locally?

**Comment by ralphlange** [comment]
Travis fails because I added tests that show issue #11 but that was never fixed. There is a partial fix in PR #21 - that fixes one of the three tests that are failing.
Maybe the tests should be skipped?

**Comment by bfrk** [comment]
@ralphlange if there is a way to disable/skip only this one (failing) test until someone has an idea how to fix it, this would be the way to go, I guess.

**Comment by ralphlange** [comment]
OK, will do.

**Comment by bhill-slac** [comment]
Re the changes to gateVc.cc in 9d76941 ENH: Add ca putLog support
The #ifdef WITH_CAPUTLOG changes could be separated out into their own commit.
The gateway supports a simple put log w/o caPutLog support which doesn't show the value.
I changed this to replace the simple put log entry w/ the new global_resources->putLog() call
which shows the same info w/ user, host, and value as caPutLog_Send().

The changes further down related to smartCopy and #if DEBUG_GDD and DEBUG_EVENT_DATA
fix crashes if DEBUG_GDD is enabled.   There's also a #if logic fix for when to call
heading("*** gateVcData::copyState: end", name());
There are also a couple of style/whitespace changes near the end that could also be broken out.

**Comment by ralphlange** [comment]
Thanks. This pull request has been integrated manually.

**Pull request closed without merging**
