### PR TITLE
Test updates to improve compatibility

### PR DESCRIPTION
**Pull request by anjohnson**
Make tests compatible with python 3:
+ Ran '2to3 -w -n *.py'
+ These should still work on python 2, Travis will confirm.

I have some Makefile changes I haven't committed yet, hence this is a draft PR...

### CODE REVIEW

**Comment by anjohnson** [comment]
Rerunnin the Travis 3.15 STATIC build which failed the first time, interestingly that's my configuration too...

**Comment by anjohnson** [comment]
It worked the second time — transient problem. Currently collecting evidence for an email...

**Comment by ralphlange** [comment]
These changes look very straightforward.

**Comment by anjohnson** [comment]
Added some slightly less straight-forward changes, mostly to the test Makefile. Being able to re-run `make tapfiles` when one of the tests seg-faults is useful, and now `make test-results` and `make clean-tests` work too.

Unfortunately Travis seems to be having problems starting some of the builds right now (it currently reports "Partially Degraded Service" due to unreliable network connectivity) although the 7.0 builds did succeed. I will attempt to re-trigger the others later.

**Comment by ralphlange** [comment]
What's your motivation for running all tests separately?
One of the main features of a test runner like `nosetests` is that it finds the test without having to configure them explicitly.

**Comment by anjohnson** [comment]
Motivations: When one of the tests dies without creating the .tap file (as was happening quite frequently for me, usually `TestEnumPropertyCache.py`), being able to re-run just that test without working out which one it was and remember how to do that by hand. `make -k tapfiles` is useful too in the face of frequent failures. Also I can completely disable a test by commenting it out of the Makefile — I don't know how to do that without editing the test program when `nosetests` finds the tests itself (with this change we give it the list of tests to run, so commenting out works with both the tapfiles and runtests targets). Your original Makefile had to list the test files anyway to install them, so there isn't really a difference in the configuration requirements.

Thanks for merging this.

**Comment by ralphlange** [comment]
IIRC, the copy was related to avoiding dependency issues with the 3.14 rules, but that is only a distant memory...

The auto-finding feature of test runners is more important in projects where the tests are in the same source files as the classes they test.

**Pull request merged**
